import HomeProvider from "@/context/HomeContext";
import "./globals.css";


export const metadata = {
  title: "Swio Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HomeProvider>
          {children}
        </HomeProvider>
      </body>
    </html>
  );
}
